#[theme]
##primaryColor="#575FE8"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
#font="sans serif"

[theme]
primaryColor = "#E694FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#575FE8"
textColor = "#DCDCDC"
font = "sans serif"
