#[theme]
##primaryColor="#575FE8"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
#font="sans serif"

[theme]
primaryColor = "#800040"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "F0F2F6"
textColor = "#262730"
font = "serif"
